spring:
  datasource:
    url: ${DATABASE_URL:jdbc:h2:file:./data/logistics;AUTO_SERVER=TRUE}
    driver-class-name: org.h2.Driver
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
  
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.logistics: ${LOG_LEVEL:DEBUG}